### ISSUE TITLE
Don't wget --quiet jq.  Ask the user what to do.

### ISSUE THREAD

**Issue by envygeeks** [packethost/packet-block-storage#3]
It might not be shifty to packet for this to happen but to me doing that is pretty shifty even if it's not all that bad.  Not only are you downloading a binary blindly onto your users servers assuming everything is going to be quite alright, but you neglect to even verify said download and make sure it's specific version.

Why not just install jq by default as well? Or install it from apt?  It's in the repositories...

**Comment by envygeeks** [comment]
Just so things are clear: https://github.com/packethost/packet-block-storage/blob/22effe411d23bb60b24ea9e19dc365728623a7dd/packet-block-storage-attach#L32

**Comment by crunchywelch** [comment]
@envygeeks agreed, this is a hack done in the interest of time IMO. will work on a fix, thanks for submitting an issue!

**Comment by vielmetti** [comment]
#7 is related; the installed binary is the wrong architecture on aarch64 servers.

**Comment by mmlb** [comment]
IMO we shouldn't be fetching jq. I'd be down for some packages probably via fpm that we could add to here as a download.

**Comment by displague** [comment]
I assume #8 has since fixed this, @vielmetti ? jq is being installed via Yum and Apt, no longer fetched via wget.

**Comment by vielmetti** [comment]
Yes, the wget is no longer in the script. Closing.
