### ISSUE TITLE
jq dependency fails on aarch64

### ISSUE THREAD

**Issue by vielmetti** [packethost/packet-block-storage#7]
if you run this script on an aarch64 machine, and it doesn't have jq installed, the script will fetch the x86 version of jq and it will fail.

Easiest fix is to make it clear in the README that jq should be installed along with other dependencies.

**Comment by vielmetti** [comment]
We're seeing this again on CentOS 7 on Packet Type 2A, where the default install does not include jq. (Ubuntu is fine.)

**Comment by vielmetti** [comment]
bump for @dlaube

**Comment by displague** [comment]
I assume #8 has since fixed this, @vielmetti ?  Both Yum and Apt installs are included now.

**Comment by vielmetti** [comment]
Closed by #8 .
